version: '1'
services:
    web:
      restart: always
#      command: bash -c "python3 manage.py makemigrations &&
#                        python3 manage.py migrate &&
#                        python3 init_admin.py &&
#                        python3 manege.py runserver 0.0.0.0:8000"
      command: bash -c "python3 manege.py runserver 0.0.0.0:8000"

      ports:
        - "8000:8000"